### ISSUE TITLE
[Bug]: redmine 5.1

### ISSUE THREAD

**Issue by ashrafalzyoud** [xmera-circle/redmine_colored_enumeration#1]
### What did you expect?

![colord](https://github.com/xmera-circle/redmine_colored_enumeration/assets/50211455/c733f93e-ce48-4935-8740-41ef8bf739d8)

### What has happend instead?

no list 

### What could be a possible solution?

be it compiable with redmine 5.1
to disable colord

### How can we reproduce the problem?

.

### In what environment are you running the plugin?

0

### Version

0.1.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liaham** [comment]
Sorry, for my late reply. I tested the plugin with RM 5.1.3 and it works as expected. Therefore, I will close this issue. Feel free to open a new issue if your problem persists.
